# Generated by Django 6.0.3 on 2026-03-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
