# Generated by Django 6.0.3 on 2026-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_source_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='site_name',
            field=models.CharField(max_length=1000),
        ),
    ]
