# Generated by Django 6.0.3 on 2026-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
